### ISSUE TITLE
Article on bus factors, how to assess and how to improve it

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1045]
Author: @pagrubel 
EB member: @markcmiller86 

I've encountered people in our community who are not familiar with the phrase "bus factor".  While perhaps not a primary metric, I think it is worth people being aware and thinking about this when they're thinking about the sustainability of their projects.  So I feel that maybe we should have an article on it. (Maybe CC or maybe a small original article.)

One important connection to make, I think, is the idea that code review is a good way to expand knowledge and understanding of parts of the code.  It is not the whole answer for improving bus factor, but it is one useful technique and a good argument for code review.

**Comment by markcmiller86** [comment]
So, what does *bus factor* mean? I don't think I've heard it except maybe in reference to microprocessor design which I don't think you are talking about here 😄

**Comment by bernhold** [comment]
Oh wow!  The bus factor is how many people have to get hit by a bus to cause problems for your project.  It could be at multiple scales -- particular portions of the code base up to the overall governance/maintainership.

If you want a less violent way to characterize it might be the number of people who need to get on a bus and ride off into the sunset...

**Comment by pagrubel** [comment]
Sounds much nicer and Mark isn't the only one who didn't know what it meant.

**Comment by markcmiller86** [comment]
Ah, ok, thanks! I guess I've heard that same *factor* described in terms of a plane instead of a bus :wink:

So, higher numbers for `bus factor` are better, right?

During ECPAM in Knoxville a few years back, one of the hopper flights from Nashville (I think) to Knoxville was full of ECP people...like maybe 50-60 people. Seemed like a bad idea and we all were thinking it.

**Comment by bernhold** [comment]
Yes, higher bus factors are better.

There are direct flights between Knoxville and both Washington DC airports.  Those regularly have high concentrations of ORNL and UTK people (probably also Y-12).

**Comment by pagrubel** [comment]
I googled bus factor in software development (and scientific software) and there are a lot of articles out there. Here are a few that I found interesting (also the 5 Whys site has many other topics)

https://www.5whys.com/articles/the-bus-factor-why-your-best-developer-is-your-biggest-probl.html
https://www.5whys.com/articles/a-critical-chain-of-bus-factors.html
https://www.5whys.com/articles/two-techniques-to-avoid-the-bus-factor-in-your-teams-push-an.html
https://deviq.com/terms/bus-factor
https://towardsdatascience.com/maintaining-a-good-lottery-factor-1eeb2b2f52a6

After searching through some of these, I'm convinced this can be a very valuable subject and some guidance can be helpful and am moving this to topic review

**Comment by bartlettroscoe** [comment]
See the CII Best Practices [[bus_factor]](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.bus_factor):

* The project SHOULD have a "bus factor" of 2 or more. {Met URL} <sup>[bus_factor](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.bus_factor)</sup>
**Details:**
A "bus factor" (aka "truck factor") is the minimum number of project members that have to suddenly disappear from a project ("hit by a bus") before the project stalls due to lack of knowledgeable or competent personnel. The truck-factor tool can estimate this for projects on GitHub. For more information, see Assessing the Bus Factor of Git Repositories by Cosentino et al.
