### ISSUE TITLE
Restructure image directory to use subdirectories?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1050]
Now that we have the capability to use subdirectories in the `images` directory, we can consider whether it is worth adding some structure to facilitate managing (finding) the images.  **We do not have to do this!** So if everyone is satisfied with the status quo we can close this issue.

But there are > 280 files in this directory at present. There appear to be a few sizable sets and then odds and ends:
* blog hero and other images (seem to be the overwhelming majority, so this might warrant further subdivisions, e.g., by year of publication)
* BSSwF and HM photos
* There seem to be a lot of files prefixed with `Logo-`

**Comment by markcmiller86** [comment]
Just going through some issues to get a fell for what is in the current `Backlog`. A question I have about this issue is whether a failure to do anything about it now, creates potentially heavy technical debt later. For example, wait a few more years...we'll have 560 images then. If we decide then to restructure, that task will be 2x bigger than it is now. 

My inclination is to close this issue.

**Comment by rinkug** [comment]
I am going to close this issue based on the conversation above.
