### ISSUE TITLE
Add resource: Minisymposium on Sw Productivity and Sustainability 

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/bssw.io#11]
Author: Greg jarrah42

Add resource for CSE17 minisymposium.

**Comment by apieum** [comment]
Hi, I'd like to point a detail if you permit.
[People are not ressources](https://www.jrothman.com/mpd/management/2014/08/people-are-not-resources/) and the [unique link](https://www.atlassian.com/agile/agile-iron-triangle) of [What is productivity?](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/Categories/Topics/WhatIsProductivity.md) tends to introduce confusion about it. (even if it's interesting) 
In the point of view of Atlassian marketing it's understandable, because they want to convince management people to buy their tool, but if your group really focus on improving scientific software, it's an **big** detail.

**Comment by pagrubel** [comment]
David: We've done mini-symposiums and poster session that we should add to bssw.

**Comment by bernhold** [comment]
Expand this idea to cover all of the minisymposia and minisymposteria we've organized at various meetings.  (Could also pull in sessions organized by others, if they have archives.)

**Comment by rinkug** [comment]
> The intent was to create a curated content article to capture the sessions where we have archives to offer.
> 
> All of the relevant events are on https://ideas-productivity.org/events/
> * PASC 2019 minisymposium (I need to add the link to the FigShare collection)
> * SIAM CSE19 all
> * SIAM CSE17 all
> * SIAM CSE15 one

Refer to new issue #684.

This original issue is outdated and is being closed
