### ISSUE TITLE
Possible new topic: diversity, equity, and inclusion

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1165]
I can see possibly adding "Diversity, Equity, and Inclusion" under "Better Collaboration".  We're starting to have relevant content.

**Comment by rinkug** [comment]
We need to check if "Diversity, Equity, and Inclusion" are the correct wordings to use here?

**Comment by bernhold** [comment]
Lois had the idea of using *just* the word "inclusivity" as our topic.  This simplifies the implementation, since we don't have to worry about commas within the topic string (which are *not* currently supported by the front-end).

**Comment by bernhold** [comment]
Added the "Inclusivity" topic under "Better Collaboration".  Next I'll add that topic to the articles I can find.

**Comment by bernhold** [comment]
PR #1273 adds the topic to the articles I could find.  If anyone finds others, go ahead and add it there too.  Considering this done.

**Comment by markcmiller86** [comment]
In trying to review #1938, I started asking myself about the difference between the terms `Inclusion` and `Inclusivity`. I don't know if we have a full record here of why we decided upon `inclusivity` over `inclusion`. But, after reading a number of sources and asking ChatGPT, I see a few differences in these two terms...

* **Inclusivity**:
   * ChatGPT says *Use inclusivity when referring to the broader principle or quality of being inclusive, or when discussing the design and intention behind policies and environments.*
   * Used **20x less frequently** according to [Google's NGram Viewer](https://books.google.com/ngrams/graph?content=inclusion%2C+inclusivity&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3). That may actually be a beneficial attribute if our goal is to widen the reader's understanding of the topic beyond the headline grabbing aspects of DE&I.
   * `Inclusivity` characterizes an approach or process aimed at achieving the end state.
* **Inclusion**:
   * Its often the `I` in `DEI` or `DE&I`. The `I` there is for the word `Inclusion`, not `Inclusivity`...though that is a tad surprising since the `D` and `E` words end in `ity`, it would make sense to select `Inclusivity` for the `I` word. But, I don't think I've seen that much or at all.
   * More closely associated with `DEI` than `Inclusivity` is.
   * ChatGPT says *Use inclusion when focusing on the specific actions, practices, or state of being included within a group or structure.*
   * `Inclusion` characterizes a state of being...of being included

A metaphor to help...Two English words that illustrate the difference between the "-ion" and "-ity" endings, similar to "inclusion" and "inclusivity", are "formation" and "formality".

1. **Formation (ending in -ion)**: This term refers to the state or process of being formed or structured. It's about the actual act or event of creating something.

2. **Formality (ending in -ity)**: This word refers to the quality or state of being formal or conforming to established practices. It's more about the characteristic or condition of something being formal.

In these examples, "formation" is like "inclusion" – it's about the act or state itself. "Formality," like "inclusivity," is about the quality or nature of something. These examples can help in understanding how "inclusion" (the state of including) differs from "inclusivity" (the quality of being inclusive).

* https://ell.stackexchange.com/questions/284149/i-wonder-if-inclusivity-would-be-better-than-inclusion-in-this-scenario
* https://thecontentauthority.com/blog/inclusivity-vs-inclusion
* https://www.forbes.com/sites/paologaudiano/2019/01/22/eight-reasons-why-we-need-to-focus-on-inclusion/?sh=66911ac8148d
