### ISSUE TITLE
Identify and tag existing articles in new topics

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1377]
We're in the process of adding several new topics to the site (#1378, #777).  Once that's done, we need to review existing articles and tag appropriate ones with the new topics (in the metadata block).

- [ ] Better Planning --> Software Sustainability (note: just because it has the word "sustainability" doesn't necessarily mean it should be included under this topic)
- [x] Better Performance --> Cloud Computing
- [x] Better Performance --> Big Data
- [x] Better Reliability --> Peer Code Review

**Comment by bernhold** [comment]
@markcmiller86 --> Big Data
@bartlettroscoe  --> Software Sustainability
@bernhold --> Cloud computing

Action: PRs with changes to topic metadata

**Comment by markcmiller86** [comment]
I want to mention, in some instances, it might be necessary to add *both* the new **topic** you are assigned to review for and also a new **category**, right? 

I mean, we can't add `big data` as a *topic*, without also ensuring `performance` is one of the categories.

**Comment by markcmiller86** [comment]
I am noticing we have some duplication...

```
% ls Site/Categories/
Collaboration.md	Performance.md		Reliability.md
Development.md		Planning.md		Skills.md
% ls Site/Topics/
Collaboration.md	Performance.md		Reliability.md
Development.md		Planning.md		Skills.md
```

In comparing `Performance.md` in both places, it appears to me the stuff in `Site/Topics` is most up to date. For example, it includes the `big data` topic. It also includes a heading for **Child Topics** as well as relative ordering of those topics.

Is the stuff in `Site/Categories` still used.

**Comment by bernhold** [comment]
The stuff in Site/Categories is not used any more.  Someone was supposed to delete it, but obviously it hasn't happened yet.  I'll do it now.

**Comment by bernhold** [comment]
PR #1468 addresses the cloud computing topic.

**Comment by markcmiller86** [comment]
PR #1463 addresses the big data topic.

**Comment by rinkug** [comment]
@bartlettroscoe : any update on this?

**Comment by bartlettroscoe** [comment]
Thanks for reminder.  I will try to get to this on Friday.

**Comment by rinkug** [comment]
@bartlettroscoe : I took a shot at finding some articles related to software sustainability. Can I create a PR and get this done this week since I have some time?

- https://bssw.io/items/what-is-sustainability
- https://bssw.io/items/software-sustainability-institute-guides
- https://bssw.io/items/an-introduction-to-the-software-sustainability-institute
- https://bssw.io/items/a-collection-of-resources-for-sustaining-open-source-software
- https://bssw.io/blog_posts/maintainers-drive-software-sustainability
- https://bssw.io/blog_posts/the-workshop-on-sustainable-software-sustainability
- https://bssw.io/blog_posts/urssi-conceptualizing-a-us-research-software-sustainability-institute
- https://bssw.io/blog_posts/software-sustainability-in-the-molecular-sciences
- https://bssw.io/blog_posts/a-community-of-practice-around-peer-review-for-long-term-research-software-sustainability
- https://bssw.io/blog_posts/data-driven-software-sustainability
- https://bssw.io/blog_posts/bloodsuckers-banshees-and-brains-a-bestiary-of-scary-software-projects-and-how-to-banish-them
- https://bssw.io/blog_posts/making-open-source-research-software-visible-a-path-to-better-sustainability
- https://bssw.io/events/the-first-international-workshop-on-the-body-of-knowledge-for-software-sustainability-bokss-21
- https://bssw.io/events/webinar-software-sustainability-lessons-learned-from-different-disciplines
