### ISSUE TITLE
Possible Blog Article: Long-term Software Gardening Strategies To Grow Better Scientific Development Ecosystems

### ISSUE THREAD

**Issue by d33bs** [betterscientificsoftware/bssw.io#1540]
## Long-term Software Gardening Strategies <br>To Grow Better Scientific Development Ecosystems

Authors: Dave Bunten(@d33bs)<sup>1</sup> and Gregory P. Way(@gwaybio)<sup>1</sup>
<sup>1</sup>University of Colorado Anschutz Medical Campus

### Abstract

Research software education organizations such as [The Carpentries](https://carpentries.org/) have compared software development to carpentry practices<sup>[1](#1)</sup>, which has had broad, positive impacts for scientific research software. However, software carpentry’s focus on static output is fundamentally limited. Namely, carpentry does not address techniques and strategies for dynamically evolving or unpredictable aspects of the software craft, such as [software rot](https://en.wikipedia.org/wiki/Software_rot) prevention, community-driven apprenticeship, and emergent design strategies. Instead, the concept of “software development as gardening” illuminates these additional realities of software development.<sup>[2](#2)</sup> The conceptual framework of software gardening underscores the value of continuous adaptable stewardship throughout the lifespan of a project, addressing risks of long-term software carpentry and community fragility. Therefore, coupling the day-to-day software carpentry mindset with a long-term focus on software gardening is likely to further advance the quality and sustainability of scientific software. In this article, we expand upon existing knowledge on scientific software carpentry by delineating good software gardening practices to encourage long-term, sustainable scientific software code and communities.

### References

<a id="1">1.</a> Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, et al. (2017) Good enough practices in scientific computing. PLOS Computational Biology 13(6): e1005510. https://doi.org/10.1371/journal.pcbi.1005510 
<a id="2">2.</a> Hunt, Andrew and Thomas, Dave. The Pragmatic Programmer : From Journeyman to Master. Addison-Wesley. https://learning.oreilly.com/library/view/the-pragmatic-programmer/9780135956977/

**Comment by bernhold** [comment]
Dave and Gregory, thanks for proposing a blog article for inclusion in BSSw.  I think the topic is very apropos, and we'd welcome your contribution.  The next step would be for us to agree on a target date for a draft of your article.  This is primarily a tool, for both us and you, to help keep it on our radar screens and plan for the work needed.  Dates can be revised if needed.  

I'm appending some more information about our blogs and the process we use below.  Please let us know if you have any questions or concerns.

Thanks!

## Submission and Publication

* Blog articles appear here: <https://bssw.io/blog_posts> and are also announced in the monthly BSSw email digest (<https://bssw.io/pages/receive-our-email-digest>).  You are certainly welcome to draw attention to your article through social media and other opportunities.
* The BSSw site is backended by a GitHub repository, and articles are produced in Markdown.  If you're comfortable with git and GitHub, feel free to give us a pull request with the draft of your article.
  - A skeleton blog article that you can copy and customize is: <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/BlogArticleSkeletonA.md>
   - You PR should add your article as a new file in the blog directory:  <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Articles/Blog>
* Or of you prefer, you could instead provide text in some convenient format (e.g., MSWord) via email.  Some authors prefer that approach.
* We can work with you on the timeline.  We sometimes schedule articles to come out in conjunction with some event – in advance, or as follow-up.  But in the absence of a specific target, we’ll work it into our pipeline.  Publication dates sometimes need to be revised, since we have multiple blog articles in flight.
* We like to allow a minimum of three weeks from draft to publication, so that we have time for our review and technical editing process and also work together with our designers to develop an accompanying image (optional).

## Content

* Length is flexible.  We generally want to keep these as a light read.  We suggest length of 500-1,500 words, though both shorter and longer may be perfectly reasonable for some topics. You can peruse past blog postings to get a feel for what we’ve published in the past.
* In the spirit of a "light read", we ask you to limit your use of figures, tables, and links.
* At the top of your article, we can include a "hero" image, which is also used as a background to highlight it as the newest article in the list of blog postings.  This image is *optional*, but if you have ideas for an appropriate image please let us know. Many blog articles are published without hero images. Guidelines for "hero" image:
  - wide rectangular shape; we can crop an image to the required size (1125 x 432 pixels)
  - the design brief for our site focuses on three types of imagery for hero:
    - stock images (we have access to a number of stock photo libraries),
    - data visualizations, or
    - people in trainings, workshops, conferences, or other settings
  - "hero" images should contain no bold text; incidental text (in diagrams, for instance) is OK.
* We request a brief bio for each of the authors
  - 50-100 words, in paragraph form, can include hyperlinks
  - Mention your current position, employer, a bit about your background
  - Include info about your interests related to software productivity and sustainability
  - Anything else you want to mention
* We use GitHub profile information (particularly photo and affiliations) to construct our Site Contributors page: <https://bssw.io/items/authors/>.  Please let us know your GitHub username. We encourage you to include a photo and up-to-date institutional affiliation in your GitHub profile.

**Comment by d33bs** [comment]
Thank you so much @bernhold, we're excited to contribute! @gwaybio and I are in discussions about the timeline and will follow up on this topic soon.

**Comment by d33bs** [comment]
Hi @bernhold - @gway and I would like to propose a draft target date of June 5th 2023. Would this work for you and BSSw? Thank you in advance for your help and feedback.

**Comment by bernhold** [comment]
That sounds great, we look forward to it!

**Comment by bernhold** [comment]
Hi @d33bs @gwaybio, I wanted to check in with you to see how things were progressing?  Is 5 June still a good date for a draft?  Thanks
