### ISSUE TITLE
Setting service level agreements for (outside) article suggestions

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1578]
We've talked about prioritizing outside submissions in particular.  But recently, we've had several that have languished for longer than seems desirable without being acted upon.  

I propose that we should set some deadlines for ourselves, and develop some mechanisms to help highlight such submissions and act on them promptly.  

I think events are probably top priority.  They are always time sensitive, and we'd really like to have people submitting "their" events rather than having to go out and find them for ourselves.  Blogs are probably next priority from my perspective.

**Comment by bernhold** [comment]
This action looks potentially useful: https://github.com/marketplace/actions/verify-user-membership

**Comment by bernhold** [comment]
In addition to trying to identify outside submissions automatically, we might want assign an EB member to take responsibility for triaging new issues within some time of arrival.  We'd probably need to rotate this around fairly frequently.

A related idea would be to have an "event editor" position on the EB with the responsibility for getting event submissions posted quickly.  This would also probably have to be rotated fairly frequently.

**Comment by rinkug** [comment]
External submissions need to be ACKed as soon as possible. Events are more time sensitive and we want to ideally highlight them in the digest. Submitted events take priority over current content writing.

The Plan
- @rinkug  responsible till end of May for monitoring external submissions. Team needs to revisit this to assign a new person at start of June.
- When PR is created - for example for a submitted event - please connect it with the issue so that. Please also leave a comment indicating who is driving it to completion so that everyone knows its being take care of.
- Content calls: We spend 5 minutes glancing at new backlog column items on the content development board.  No voting but just triaging.
- We will explore automatic actions in github to monitor new submissions outside of EB team.  (To be done: by @markcmiller86). The following automatic actions are to be considered:
  - Send email to editorial team
  - Setup automatic label against submitted issue.

**Comment by bernhold** [comment]
https://github.com/marketplace/actions/send-email may be useful to send email

**Comment by bernhold** [comment]
Someone has started manually (I assume) adding "external contribution" labels to some recent issues and PRs.  

For the record, I'll note that the idea we discussed of automatically applying the label based on whether or not the author of an issue/PR is a member of either the BSSw EB team or the BSSw support team (in the GitHub Teams sense) would *not* have labeled #1573.  Mark created that PR.

In my opinion, this is okay.  The important thing, as far as I'm concerned, is catching that initial interaction and ensuring that we respond in a timely manner.  And going directly into a GitHub issue or PR is the route we have been tending to miss, hence the idea of using an action.  PR #1573 was not the initial contact with Robert Underwood.  That came by email, as I recall, and then we looked over Robert's writing to identify what we thought was a good article to start with.  So Mark's PR is at least two steps removed from that initial contact.

But I'm making this note in case others were thinking differently.  Speak up!

**Comment by markcmiller86** [comment]
> Mark created that PR.

Yes and no. I did indeed create the particular PR that was ultimately used in preparing the article. However, Robert initially submitted the PR as #1570. But, because that was from a forked repo, I was not able to create a *stacked* PR that Robert could then merge into it. So, I copied the article out of #1570 to start #1573

So, with an action, PR #1570 would have indeed recieved that new label.

**Comment by rinkug** [comment]
I created the label manually. Pls delete if its messing up things.

Yes, with an action, PR #1570 would have received that new label. @bernhold - I am ok with your approach.

**Comment by rinkug** [comment]
@bernhold : are we happy with the label approach? It seems to be working well.

**Comment by rinkug** [comment]
As discussed on Dec14, we are closing this. We have not addressed the core issue of policies but we have a label in place to monitor.
