### ISSUE TITLE
Possible Blog Article: nix for isolated and pkg mgr agnostic reproducible environments

### ISSUE THREAD

**Issue by majidaldo** [betterscientificsoftware/bssw.io#1689]
I'm been learning about nix https://nixos.org/ and I'm just blown away by its power. It generally doesn't register with scientific programmers though!

Willing to contribute once I learn more but putting it here to see if it makes sense.

**Comment by bartlettroscoe** [comment]
@majidaldo, let us know what you find out about this.

**Comment by bartlettroscoe** [comment]
This sounds very similar to [Spack](https://spack.io/).  How similar is NIX to Spack?

**Comment by bernhold** [comment]
@majidaldo thanks for drawing this to our attention.  We tend not to emphasize general principles of software engineering over specific products.  For example, we recently published a [blog post](https://bssw.io/blog_posts/julia-s-value-proposition-for-better-scientific-software) that is nominally about the Julia language.  But it looks at it from the perspective of some of the things they've built into the language and ecosystem that facilitate better software engineering practices.  So that might be a thinking cap to use if you'd like to contribute a blog article on NIX.

Though from your last comment, it sounds like it might not be sufficiently mature yet.  Please keep us informed if you continue digging into it.  Thanks

**Comment by majidaldo** [comment]
> @majidaldo thanks for drawing this to our attention. We tend not to emphasize general principles of software engineering over specific products. For example, we recently published a [blog post](https://bssw.io/blog_posts/julia-s-value-proposition-for-better-scientific-software) that is nominally about the Julia language. But it looks at it from the perspective of some of the things they've built into the language and ecosystem that facilitate better software engineering practices. So that might be a thinking cap to use if you'd like to contribute a blog article on NIX.
> 
> Though from your last comment, it sounds like it might not be sufficiently mature yet. Please keep us informed if you continue digging into it. Thanks

nix is 20 years old! :D

**Comment by majidaldo** [comment]
> 



> This sounds very similar to [Spack](https://spack.io/). How similar is NIX to Spack?

similar. i don't know enough to compare and contrast.

**Comment by majidaldo** [comment]
update:

I feel like this belongs at a lower level than what the programmer would manage. It's much like a build system. 

An interesting use of nix would be as an "implementation" of programming-language specific reproducibility. For Python it's things like [poetry2nix](https://github.com/nix-community/poetry2nix/issues/1183) (but i'm encouraging implementing pyproject.toml)

**Comment by bernhold** [comment]
@majidaldo do you still see a blog article in this somewhere?  Sounds like perhaps you've changed your mind?

**Comment by majidaldo** [comment]
> @majidaldo do you still see a blog article in this somewhere? Sounds like perhaps you've changed your mind?

yes. it's too low level for bssw. it does have its place though in infrastructure.
