### ISSUE TITLE
Possible Blog Article: Come for Syntax, Stay for Speed, Understand Bugs - An Analysis of Bugs in Julia Programs

### ISSUE THREAD

**Issue by akondrahman** [betterscientificsoftware/bssw.io#1859]
Greetings, 

I recently authored a peer-reviewed journal publication on the [common bugs in Julia programs](https://link.springer.com/article/10.1007/s10664-023-10328-5). As use of Julia is increasingly [becoming popular](https://www.nature.com/articles/s41592-023-01832-z) amongst research scientists and engineers, a blog post related to defects in Julia programs, could be of interest to the Better Scientific Software community. In the blog post, I will describe the major findings and their implications for practitioners for developers who contribute to scientific software projects. 

Looking forward for your feedback. Please let me know if there are further questions and concerns.

**Comment by bartlettroscoe** [comment]
FYI: @betterscientificsoftware/bssw-editorial-board

**Comment by markcmiller86** [comment]
@akondrahman I am wondering if a lower bar would be to create a curated content article (basically a very short article to simply reference the publication) might be best/easiest. Thoughts?

**Comment by bernhold** [comment]
Actually, if @akondrahman is motiviated to write a blog article about his work, I don't think we should discourage that.  I'd be happy to see any contribution about this, but a blog article would be absolutely welcome.

Here is the guidance we provide for blog authors (curated content articles are simpler and we can walk you through that if you prefer)...

## Submission and Publication

* Blog articles appear here: <https://bssw.io/blog_posts> and are also announced in the monthly BSSw email digest (<https://bssw.io/pages/receive-our-email-digest>).  You are certainly welcome to draw attention to your article through social media and other opportunities.
* The BSSw site is backended by a GitHub repository, and articles are produced in Markdown.  If you're comfortable with git and GitHub, feel free to give us a pull request with the draft of your article.
  - A skeleton blog article that you can copy and customize is: <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/BlogArticleSkeletonA.md>
   - You PR should add your article as a new file in the blog directory:  <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Articles/Blog>
* Or of you prefer, you could instead provide text in some convenient format (e.g., MSWord) via email.  Some authors prefer that approach.
* We can work with you on the timeline.  We sometimes schedule articles to come out in conjunction with some event – in advance, or as follow-up.  But in the absence of a specific target, we’ll work it into our pipeline.  Publication dates sometimes need to be revised, since we have multiple blog articles in flight.
* We like to allow a minimum of three weeks from draft to publication, so that we have time for our review and technical editing process and also work together with our designers to develop an accompanying image (optional).

## Content

* Length is flexible.  We generally want to keep these as a light read.  We suggest length of 500-1,500 words, though both shorter and longer may be perfectly reasonable for some topics. You can peruse past blog postings to get a feel for what we’ve published in the past.
* In the spirit of a "light read", we ask you to limit your use of figures, tables, and links.
* At the top of your article, we can include a "hero" image, which is also used as a background to highlight it as the newest article in the list of blog postings.  This image is *optional*, but if you have ideas for an appropriate image please let us know. Many blog articles are published without hero images. Guidelines for "hero" image:
  - wide rectangular shape; we can crop an image to the required size (1125 x 432 pixels)
  - the design brief for our site focuses on three types of imagery for hero:
    - stock images (we have access to a number of stock photo libraries),
    - data visualizations, or
    - people in trainings, workshops, conferences, or other settings
  - "hero" images should contain no bold text; incidental text (in diagrams, for instance) is OK.
* We request a brief bio for each of the authors
  - 50-100 words, in paragraph form, can include hyperlinks
  - Mention your current position, employer, a bit about your background
  - Include info about your interests related to software productivity and sustainability
  - Anything else you want to mention
* We use GitHub profile information (particularly photo and affiliations) to construct our Site Contributors page: <https://bssw.io/items/authors/>.  Please let us know your GitHub username. We encourage you to include a photo and up-to-date institutional affiliation in your GitHub profile.

**Comment by bernhold** [comment]
What do you think @akondrahman ?

**Comment by akondrahman** [comment]
I am interested in going for a blog post. Is that OK?

**Comment by markcmiller86** [comment]
> I am interested in going for a blog post. Is that OK?

Yes, for sure. My apologies for prior remark suggesting a CC.

**Comment by bernhold** [comment]
Thanks @akondrahman, we welcome your contribution.  A couple of comments back (https://github.com/betterscientificsoftware/bssw.io/issues/1859#issuecomment-1792930866) I gave our guidance for blog posts.  Let us know if you have any questions.  Thanks!

**Comment by bernhold** [comment]
Also, it might be useful to set a target date for your draft.  That can help both of us keep it on the radar, and helps with our planning.  Do you want to suggest a date that's reasonable for you?

**Comment by akondrahman** [comment]
Is a 2 week deadline acceptable ?

**Comment by akondrahman** [comment]
I have created a pull request here: https://github.com/betterscientificsoftware/bssw.io/pull/1879

**Comment by akondrahman** [comment]
A gentle reminder on the submitted pull request at: https://github.com/betterscientificsoftware/bssw.io/pull/1879
