### ISSUE TITLE
Event Notice

### ISSUE THREAD

**Issue by MariaLevchenko** [betterscientificsoftware/bssw.io#2176]
* **What:** *I Made My Code Open - Now What? Steps To A Thriving Open Software Project*

* **When:** *October 23, 2024*

* **Where:** *Online*

* **Organizers:** *EMBL-EBI*

* **Website:** *[URL for event web site](https://www.ebi.ac.uk/training/events/i-made-my-code-open-now-what-steps-thriving-open-software-project/)*

* **Summary:** *Sharing your code is a good first step towards building open source software, but it is not enough to ensure its success.*

* **Description:** *This webinar focuses on practical issues to increase impact of open software projects, including maintenance, community building, discoverability, project management, documentation, licensing, and user needs.  

Our speakers will share their experience working with the open source code as part of the CAPITAL project - open source tool that uses machine learning to identify biological concepts from text and link them to relevant ontologies. They will discuss the challenges they have encountered and potential solutions to address these.*

**Comment by bernhold** [comment]
@MariaLevchenko thanks so much for your contribution!  It has been published here: https://bssw.io/events/webinar-i-made-my-code-open-now-what-steps-to-a-thriving-open-software-project

If you have other general events of this type, we would welcome future submissions from you and your colleagues.  A few tips that might help with future submissions:
1) We'd prefer to receive a PR rather than an issue.  You can use the source file for this event as a template for future submissions: https://github.com/betterscientificsoftware/bssw.io/blob/main/Events/2024-10-whats-next.md.  If the nature of the event is different next time, just do your best.  We'll do an edit pass and can fix things up then.
2) At the end of each month, we email a summary of new content to about 900 subscribers.  If you can get your events published before the end of the preceding month, we'll also feature them in the email digest.  Ideally, you'd submit your PR 2 weeks before the end of the month so that the editing and publication process has slightly less urgency.

For my own information, do you make recordings of these webinars available after the event?  I also give tutorials, and I'm interested in your content, but I'm not sure I'll be able to attend the live event. (And this is also something that might be worth highlighting in the webinar event.)

Thanks again, and we hope your webinar goes well!

**Comment by MariaLevchenko** [comment]
@davidbernholdt thank you!
Re: webinar recording. 
Yes, the webinar is recorded and recording is added to the event page, so even if you view the page after event has ended you should be able to access it. I'll make sure to add this info to the event page.
Re: using PR instead of an issue
Thank you for pointing that out! I'll make sure to do that next time. I've followed guidance here: https://bssw.io/pages/how-to-contribute-content-to-better-scientific-software. It was my first ever interaction with GitHub, as my role is in outreach and not technical development. I just wanted to highlight how helpful I've found the documentation and contributor guidelines - for someone with zero experience it went surprisingly smooth. Thank you for adding and maintaining these.
