### ISSUE TITLE
Recommend pulling eveything in CI check to pre-commit hook

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#334]
We have CI checks enabled in travis here. Thats great but...nothing I see happening there is anything we cannot do as a pre-commit hook. Pre-commit hooks are way faster and use less resources. They don't require waiting for a CI instance to boot.

This is a note to self...to move all of that to a pre-commit hook. That does require that cloners know to install those hooks but I think we can manage that.

**Comment by rinkug** [comment]
We need to have a conversation on this when we discuss workflow.

**Comment by bartlettroscoe** [comment]
Pre-commit  hooks don't work if people edit files directly on GitHub.

**Comment by markcmiller86** [comment]
Well, I hadn't meant to *replace* ci checks with hooks but only to write as much of the ci scripting logic as makes sense to allow someone to run them as hooks if they wanted. That way, someone can get fast turn around locally and when they finally *push*, be reasonly assured the push won't fail CI.

But, I am not married to the idea so if others feel like closing this, lets close it.

**Comment by bartlettroscoe** [comment]
> Well, I hadn't meant to replace ci checks with hooks

@markcmiller86, I am actually a fan of pre-commit hooks as long as they are very fast.  And you can always skip them with `git commit --no-verify [other args]`.   I just have never worked with any projects that were willing to use them.

**Comment by bernhold** [comment]
Seems like we should revisit this question in the context of GH actions.  If we can get what we want via actions, I'd be inclined to go that way.  

If not, then I need to understand a little more about pre-commit hooks.  In particular, I think those run on the contributor's local system, is that correct?  If so, I'm somewhat concerned about how supportable and maintainable this is (maybe that's what underlies @bartlettroscoe 's comment about "I've never worked with any projects that were willing to use them".  Maybe for the EB it would be manageable, but for outside contributors, who we're trying to cultivate and make their life easy?  Also, how to pre-commit hooks work if your contributing directly through the GH WUI?  Or if you're using git via GH Desktop rather than directly?

**Comment by bartlettroscoe** [comment]
You really want both local checks and GHA checks in PRs.  We just set up a Git project to use codespell and it does spell checking in local testing and once pushed to GH with GHA checks.  If you are working just on GH, you have to just rely on GHA checks.

**Comment by rinkug** [comment]
This is not a priority since we are doing action post-commit anyways.
