### ISSUE TITLE
Behavior of reviews on PR and adding new commits

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#362]
CC: @curfman, @markcmiller86, @bernhold, @prwolfe

As discussed in the BSSw meeting today, we discussed the fact that the PRs in this bssw GitHub project does not seem to remove the "check mark" on reviews when new commits are pushed.  For example, I approved the PR #351 and @markcmiller86 pushed new commits and GitHub still showed that I approved the PR.  As we discuss, there are pros and cons to this.  But in the Trilinos GitHub repo, when new commits are pushed to a PR branch, all of the existing approvals are changed to comments, therefore requiring someone to approve again.  My opinion is that the behavior in the Trilinos GitHub is the better behavior (but we can debate that).

This issue is to investigate this behavior and figure out how to manipulate this behavior with GitHub and what triggers it and decide what behavior we want.

**Comment by bartlettroscoe** [comment]
My guess is that the Trilinos GitHub repo behavior is triggered by requiring PRs to be approved before they can be merged.  The page:

* https://help.github.com/en/articles/about-required-reviews-for-pull-requests

does not state this specifically but that would be my guess.

My opinion is that we should protect the 'master' branch require 2 official approvals for every PR before it can be merged.  But a select number of people can be allowed to make direct changes to 'master' for purposes of managing the metadata and the BSSw update.

**Comment by markcmiller86** [comment]
> My opinion is that we should protect the 'master' branch require 2 official approvals for every PR before it can be merged.

I am fine with that. Seems reasonable.

> But a select number of people can be allowed to make direct changes to 'master' for purposes of managing the metadata and the BSSw update.

I think anyone who is an *owner* can commit directly to master if modifying directly on GitHub (I've made this mistake a few times on VisIt). If modifying locally and trying to push to master, its concievable there could be hooks that prevent that.

**Comment by markcmiller86** [comment]
BTW...because of the additional YAML gymnastics involved in going from *master* to live on the generated site, I would not like to burden **EB Members** with having to submit PRs to do that. They should be allowed, I think, to modify YAML directly on master. I dunno if there are a variety of *other steps* **EB Members** wind up having to take to marshal a *finished* article through in preparation for going live but none of that do I think should required a PR. That would be onerous and not very useful to revision history either.

**Comment by markcmiller86** [comment]
FYI...I figured out where we need to go do to this. See picture below from Settings. I started to enter a new (first one) Branch Protection Rule.

We don't have any rules set up yet so I did NOT proceed. But, this is how we'd do it. Check the `Dismiss stale pull requests when new commits are pushed`

<img width="861" alt="Untitled" src="https://user-images.githubusercontent.com/5720676/58362460-f9cb2d80-7e4b-11e9-8047-2939e5d479f6.png">

**Comment by bartlettroscoe** [comment]
@markcmiller86 we should bring this up at the next BSSw meeting and recommend this.  Note that your prior reviews don't go away.  They just change from approvals to comments.  You can still read them.

**Comment by bernhold** [comment]
> BTW...because of the additional YAML gymnastics involved in going from _master_ to live on the generated site, I would not like to burden **EB Members** with having to submit PRs to do that. They should be allowed, I think, to modify YAML directly on master. I dunno if there are a variety of _other steps_ **EB Members** wind up having to take to marshal a _finished_ article through in preparation for going live but none of that do I think should required a PR. That would be onerous and not very useful to revision history either.

I think that eventually, we may want to a setup where we can leverage branches in the repo to control previewing and publication.  This is obviously more in line with traditional git workflows, and I think makes some of the mechanics a little easier.  It will require changes on the frontend site, but I don't *think* they'll be major.

In the mean time, I do agree that we should allow **EB members** and **Editorial assistants** to be able to flip the publish switch, and probably even make other metadata adjustments without the need for a PR.

**Comment by markcmiller86** [comment]
@bernhold ... It turns out *owners* have god-like powers in the repo. This includes being able to modify directly on master even when there are branch protection rules enabled.

So, enabling branch protection rules will have the effect @bartlettroscoe has recommended but will not then *also require* **EB Members* (assuming they are also *owners* of the repo) to is PRs for all changes, even those that make sense.

That said, another way around the kinds of things that **EB Members** need to perform, *easily* (meaning without having the gymnastics of PRs), is maybe to have CI scripts that do it on-demand when requested.

**Comment by rinkug** [comment]
This is not a big issue for us now. So we leave it as is and close it.
