### ISSUE TITLE
Create policy regarding content behind paywalls

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/bssw.io#414]
It was bought up in today's discussion that we need to decide whether we
will consider articles behind paywalls on the bssw.io website. If we
consider them, what are the rules and where do we draw the line?

The article that prompted this discussion was:
https://medium.com/@alltopstartups/this-personal-kanban-approach-is-the-simplest-way-to-give-up-multitasking-and-get-real-work-done-c126c9ad25b1

**Comment by markcmiller86** [comment]
I am against direct links to any content behind paywalls (or regwalls) of any kind, even *soft* ones. I don't want to see BSSw.io encourage that form of content hosting. I never follow them myself or when I do, I never register or pay to see the full article.

I think its fine to cite such articles using standard textual bibliographic data but actual url links I would like to avoid entirely.

A slightly less provincial (usage?) approach I could get behind is to flag such links with the 🔒 emoji (and perhaps in a different/bad color) so that visiters know what they are getting before they follow such links.

**Comment by bernhold** [comment]
I see two "axes" to this discussion: first the forms of walls, and second our philosophy w.r.t. openness.

For the first, let me propose some terminology of different types of "walls"
1. Soft walls, typically allowing some number of article view per month before imposing any restrictions
2. Registration walls, requiring registration but not charging any money
3. Institutional subscriptions, typical of academic journals.  Content is pay-to-view to the general public, but many institutions will have subscriptions to many sources.  On the other hand, no institution can afford to subscribe to everything, and some BSSw readers might not be associated with institutions with such subscriptions
4. Hard paywalls, where content is strictly pay-to-view

Then there's the philosophical side.  Does BSSw want to restrict itself to pointing to open content?  Where do we draw the line? What about books?  What about paid MOOC courses?  What about articles that refer to commercial software?

I am concerned that @markcmiller86 's view is too limiting.  I don't feel that BSSw should be limited to open resources as a philosophical matter (which is more or less how I read Mark's comment). 

I would draw the line at resources we could reasonably expect our audience to have some access to.  My intent here would be primarily to exclude hard-paywalled sites where institutional subscriptions (to get around them) are unlikely.  Unfortunately, things like books and paid MOOC courses don't fit this line particularly well.  So maybe that's not the right line.

As to marking resources as paid, I would say "yes, but".

Yes, but a single lock emoji doesn't convey any of the subtleties of the various "degrees" of walls that I laid out above.  Many people might easily access an article on medium.com and not be bothered by the wall.  To me, that doesn't warrant a lock.

Yes, but I don't think it is desirable to put any such indicator in the *title* as @jarrah42 suggested on the phone today.  In the body somewhere would be more appropriate to me.  Let them read why someone thinks the article might be useful, *and* see that it might be walled and make the decision.  Don't scare them away when they're looking at a list of titles resulting from a search or something.

More than two cents, I guess, but there we are.

**Comment by jarrah42** [comment]
I guess I'm somewhere between the two. I'm not fussed if we host content that links to these sites, but I want to know before I waste time reading the curated article, so I would like it indicated in the title. I agree there are different degrees here, so I'd be happy with using something like (and these are just examples):

(limited access)
(requires registration)
(requires subscription)

**Comment by bernhold** [comment]
@jarrah42 I was wondering if there was a "plush" version of the lock emoji to indicate softer walls :-)

**Comment by bartlettroscoe** [comment]
My view is that we should be free to point to any content that we think would be useful.  Paid books are a great example.   (There just is no free well-written and organized replacement for "Code Complete 2nd Edition" that I know of.)  Note that people's time reading some material is far more expensive than access to the material itself.  For example, SNL paid like $40 for "Code Complete 2nd Edition" but likely paid thousands for my time reading that entire book.  But to get the same info from free sources would likely have costed many times that in my time looking for and reading the material.  Hopefully projects and institutions understand this.

**Comment by jarrah42** [comment]
As long as it is flagged in the subject, I don't mind.

**Comment by bernhold** [comment]
@jarrah42, I still have a problem with putting this on the subject line specifically. I think this is an inappropriate level of gatekeeping, and doesn't provide both sides of the story to the reader. Presumably the body of the article would help make the case that the resource is worth whatever it costs.

I'm okay putting it early in the body.  Rinku's been revising things to have some key into in a table at the top of the article.  We could even add a row to the table to indicate the paywalledness of the resource.

**Comment by jarrah42** [comment]
In my view the issue is knowing that the article is restricted and/or requires payment before clicking on a link to the curated page. I think that is the accepted approach to this issue, and is how most news sites operate. If that can be done with an icon on the page that lists all the curated content, then fine, but even having it at the start of the article is deceptive because I'm forced to go to the page before deciding if I'm interested in proceeding or not. The subject should be descriptive enough to decide if I want to pay or at least find out if the content is worth paying for.

**Comment by bernhold** [comment]
@jarrah42 I'm concerned about expecting the title alone to provide enough information to allow someone to decide if they're interested in pursuing a paid resource.

We already have a lot of examples on the site of cc articles pointing to paid resources.  I'm guessing their titles are not sufficiently informative as they are now, since that was not a criteria when they were written. But perhaps you could take a look and provide some examples that you think are good, or suggest how some of the existing titles might be revised? I think a few examples would help us all better evaluate this idea.

**Comment by markcmiller86** [comment]
> I am concerned that @markcmiller86 's view is too limiting.

I want to re-iterate... *pointing* to such content is IMHO fine. The manner in which we point to it is I think the greater issue. I'd simply prefer we use textual bibliographic (e.g. non-clickable) format to *point* to such content and active links only to freely available content. The info provided in a textual bibliographic entry should be sufficient for any reader to go find it (and purchase/register) if they really wanna see it.

If we followed the format of referencing I developed in the AGC articles (footnote refs to table of citations and citations at end), then so doing is actually pretty easy.

**Comment by bernhold** [comment]
@markcmiller86 for books and journal articles and paid online courses too?

I think this approach would be quite frustrating to users to what to pursue a resource, and would lessen the value of BSSw.  (I can tell you how I feel about ORNL business tools that provide a URL that's not clickable.)  

On the other hand, those who don't want to pursue paid resources simply don't follow the link. 

So I think this approach offers only negatives.

If we want to address the concern, I think the key is to provide information about the nature of the resource.  In that respect, I agree with @jarrah42, except I would put the info in the body rather than the title.

**Comment by bartlettroscoe** [comment]
Okay, the consensus is to prefer open sites but if there is a very compelling article behind a paywall, we should allow it.  Especially now many sites will given you X articles for free (if you register).

Closing as complete
