### ISSUE TITLE
Improve organization of resources

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/bssw.io#437]
Currently, resources are organized by topic. When I go into a topic, I get a long list of items which are arranged in an unknown order. I don't find this very useful or easy to navigate for the following reasons:

1. The items include a TOPICS line, which presumably means they are included in other lists, but it is not clear. Also this information is not particularly useful, redundant, and makes the list longer.

2. The items are presumably sorted by date, but it is not clear. If it is date, the date should be displayed. Ideally the sort criteria could also be changed, e.g. to the item name.

3. Items also need to be grouped into types (e.g. webinar, link, curated content, article, etc.) Currently they are all mixed together so the only information you have to go in is the title. It is annoying to have to go into each item to find out what it is.

4. In relation to 3), it would be useful if the topic page gave the option of displaying the groups separately, or as a list sorted by group.

5. These issues are also particularly a problem when listing all resources.

6. Searching by type would also be useful, since if I search for "webinar" I currently get anything with webinar in the text. I would prefer to be able to get a list of all webinars we have published, but this is not currently possible.

Given that one of the main purposes of the site is to provide resources, I think that more time needs to be spent on making it more useful to users.

**Comment by pagrubel** [comment]
This enhancement is very important as I find it difficult to process (search) for useful information myself.

**Comment by rinkug** [comment]
The re-organizing of the resources is an ongoing process. The team has done some of the reorganization in the last several months and the website has have come a long way. But, there is a lot more pending. We need to keep track of all the wish-list of items we want for the external website, so that we know what to prioritize when we come to that phase. Perhaps on the bssw internal trello board..

**Comment by bernhold** [comment]
Related: should have define a process for periodically refreshing the topic tags we use on the site?  It would be nice to have a clear place to put proposals for "missing" topic tags, and a regular review process to decide on changes.  

Also need to keep track of the items that prompted the suggestion so that we can go back and apply the new tags once their accepted and implemented.

Another question is what does it take to implement new tags from a front-end and site design standpoint?

**Comment by rinkug** [comment]
Closing this issue and it is referenced in the broader topic of search improvements
