### ISSUE TITLE
Improving search capability on BSSw.io

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#446]
This issue will list all the potential search options that we would like to see on BSSw.io eventually..

Search options:
An advanced search that supports:
Use the form to construct your query:  support for "AND" or "ANY" for below options
* range for published dates
* author names
* topic name
* category name
* checkboxes for events, curated content, blogs
* contributor name(s)

Search capability sorting by
* publish date, 
* author
* contributor name,
* Once search results appear, click on "just events" to show events from the results, "just blogs" to show blogs from the result

Several library systems are good examples for advanced search options: for ex: https://chipublib.bibliocommons.com/search

**Comment by markcmiller86** [comment]
Here are some random thoughts...

Which of these search and sort features are *outward* facing for BSSw site visitors and which, if any, may be for *inward* facing, administrative purposes? If there is a distinction, it might help to capture that here though it may not be all that relevant either.

A big reason to stay away from the *library-like* interface to sorting is that requires a lot of work to maintain and update as needs evolve. Instead, I think its best to implement these features via textual search syntax rather than to have a page full of text boxes into which one enters different kinds of text. In other words, take a play from GitHub's playbook where searching is concerned and define a search syntax and keywords. So, to search by author, you would enter `author:<author-name>` in the 🔍 box just like [GitHub does it](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests). This kind of approach also lends itself well to implement python tools, the search string is easily encoded in and can be included in emails, etc.

Next, I can already search by category and topic though it is NOT immediately obvious how to do that from the 🔎 search text entry box. I can search by author too...if I enter `bernholdt` in the 🔎 box, I get all of David's 54 publications (nice work by the way @bernhold). Now, I probably also get entries which simply contain `bernholdt` in the text body but where David is not actually an author. Does that really matter?

What about case-sensitivity? Do we care?

I think default should be to match by *ANY* and so we only need to come up with interface to specify *AND* based searches.

If search results were presented in a columnar way with colums for things like date, title, author, category, etc. then sorting as needed would be doable by clicking on the desired column heading. In other words, we shouldn't need any special syntax to indicate how results are sorted.

**Comment by markcmiller86** [comment]
So, I am doing a little comparison of Google searches restricted to site bssw.io and bssw.io's own searches

**Search String**|**Google Hits**|**BSSw Hits**
:---|:---|:---
`mark miller`|[42](https://www.google.com/search?q=mark+miller&as_sitesearch=bssw.io)|[31](https://bssw.io/items/search?search_string=mark+miller)
`"mark miller"`|[42](https://www.google.com/search?q="mark+miller"&as_sitesearch=bssw.io)|[17](https://bssw.io/items/search?search_string=%22mark+miller%22)
`continuous integration`|[219](https://www.google.com/search?q=continuous+integration&as_sitesearch=bssw.io)|[50](https://bssw.io/items/search?search_string=continuous+integration)

**Comment by rinkug** [comment]
We have finished phase 1 search implementation.

**Comment by rinkug** [comment]
I think we will be stopping with phase1 implementation. Thus this can be closed.
