### ISSUE TITLE
Consider switching "BSSw Internal" project board to the organization level

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#534]
We should consider moving the "BSSw Internal" project board:

* https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/projects/2

to the organization level:

* https://github.com/orgs/betterscientificsoftware/projects/1?

The advantages of this are that you can include issues from multiple repositories that exist under the bettersicientificsoftware GitHub organization.

**Comment by bartlettroscoe** [comment]
@rinkug, @bernhold, @curfman, @markcmiller86 

Just something to consider.  I created the private project board:

* https://github.com/orgs/betterscientificsoftware/projects/1?fullscreen=true

to demonstrate.

**Comment by bernhold** [comment]
@bartlettroscoe I propose that we can close this, for the following reasons...

* Since you started this thread, we've taken a number of actions to consolidate all of our work into a single repo, and
* This organization hosts a *lot* of repos that are not related to bssw.io and I think it would be hard for us to protect against other members of the organization making changes to our board (inadvertently, of course)

**Comment by bartlettroscoe** [comment]
>  I propose that we can close this

@bernhold.  Sure.
