### ISSUE TITLE
Full on-line book on numerical methods for engineers

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#562]
I am putting a link to this resource here because I didn't know a better place to capture it and I think its potentially a great resource. Its a full book online, just *published* in Jan of this year (2020).

http://folk.ntnu.no/leifh/teaching/tkt4140/

Its primarily mathematical in nature, more than code but it does have a lot of Python coding of some of the numerical methods described.

**Comment by bernhold** [comment]
I don't see much about the software side per se.  The section on Python coding is very terse.  It references PEP8 and says they don't completely follow PEP8 because they don't like it.  It references something from Google which is now 404.  Maybe useful for numerical analysis, but I would argue maybe not for software engineering?

**Comment by markcmiller86** [comment]
I think if its lacking sufficiently in software focus, we should close it.
