### ISSUE TITLE
Should we do an article on dealing with large pull requests

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#564]
Authors: @markcmiller86 
EB member: @bartlettroscoe 

Large PRs are a challenge. In some sense, large PRs are inherently not-agile. I've been dealing with cases where PRs involve hunderds of files, many of which are code generated but GitHub filters don't allow me to filter based on where code lives in a directory treee. GitHub has some useful features for handling large PRs including filtering, reviewed file check box, ignoring white space diffs which I've found most developers are not aware of. Also, don't know if doing a PR review locally with other tools would be easier.

GitHub has [this](https://gist.github.com/mikepea/863f63d6e37281e329f8#keep-it-small) to say about PR size. Many refs mention importance of keeping pull requests smaller...
* https://www.thedroidsonroids.com/blog/splitting-pull-request
* https://unhashable.com/stacked-pull-requests-keeping-github-diffs-small/

If nothing else, what I've learned recently is that *crafting* a PR is an important thinking cap to be wearing and it is one I don't think many code teams really think about or have developed a lot of competence and doing yet.

**Comment by pagrubel** [comment]
Valuable information here.

**Comment by bernhold** [comment]
Some projects limit the size of PRs, rejecting those they consider too large.  Usually, this is somewhat fuzzy, but there are usually at least rough guidelines or "conventional wisdom" among the development community.

**Comment by bartlettroscoe** [comment]
Below, I will post an email chain related to this topic about ideas touched on in the article:

* https://gregoryszorc.com/blog/2020/01/07/problems-with-pull-requests-and-how-to-fix-them/

but are really more general than that and get to the problem with large PRs.

I will post one comment per email below (with the names saved but the email addresses redacted).

**Comment by bartlettroscoe** [comment]
From: @markcmiller86 
Sent: Friday, October 30, 2020 2:01 PM
To: IDEAS-ECP Team (ideas-ecp@lists.mcs.anl.gov) <ideas-ecp@lists.mcs.anl.gov>
Subject: [EXTERNAL] [Ideas-ecp] An excellent read on problems with pull requests

I happened to run across this article today...

https://gregoryszorc.com/blog/2020/01/07/problems-with-pull-requests-and-how-to-fix-them/

I highly recommend a read of it. It is long! But, its caused me to re-shape my thinking regarding how to best use Git and GitHub to both review and craft good pull requests.

**Comment by bartlettroscoe** [comment]
From: @markcmiller86 
Sent: Friday, October 30, 2020 2:01 PM
To: IDEAS-ECP Team
Subject: [EXTERNAL] [Ideas-ecp] An excellent read on problems with pull requests

I happened to run across this article today...

https://gregoryszorc.com/blog/2020/01/07/problems-with-pull-requests-and-how-to-fix-them/

I highly recommend a read of it. It is long! But, its caused me to re-shape my thinking regarding how to best use Git and GitHub to both review and craft good pull requests.

**Comment by bartlettroscoe** [comment]
From: @bartlettroscoe 
Sent: Friday, October 30, 2020 7:56 PM
To: @markcmiller86, IDEAS-ECP Team
Subject: RE: [EXTERNAL] [Ideas-ecp] An excellent read on problems with pull requests

Hello Mark,

Just curious, but what did you take away from this that you found useful?

As for the blog article …

Wow, that is a long blog article.  He makes good points about the lack of support for reviewing individual commits in GitHub and GitLab.  (And I have often seen that most reviewers never even read the commit messages when doing a PR review.)  But the reality is that most projects and most people don’t really care about individual commits long ago in the past (unless something breaks and we want to trace the cause).  If the software is working, people really don’t bother reading the detailed VC history too much.  (But it is still useful to write good commits to help answer the “why” software is in the current state that it is.)

However, there are a lot of holes in what he proposes and I think a group of git gurus [would have issues with] (and blog articles are not peer reviewed).  (I am not a git guru but I can post my notes somewhere that contain some of the [issues] with what he is proposing.)

But if you sit back and think about what he is trying to accomplish:

* Focus reviews on the commit level (and thereby encouraging commits that represent “logical change sets” which has lots of positive consequences)
* Integrate “good” commits with ‘master’ quickly (to avoid merge conflicts, etc.)

you realize that Kent Beck was right all along with XP.  The way that XP accomplishes these goals are:

* Write all code using a pair programming team where each commit is fully reviewed in real-time by your partner.
* Be able to (re)run the important tests in less than 10 minutes.
* Merge to ‘trunk’ on a daily basis (or more frequently).

With git, you can create several commits in a pair-programming session locally and you can create fixup commits and combine them with their logical commits and then push these commits in batches (without bothering to create PRs).  The XP process is *so* much simpler that what he is proposing (and is simpler than the currently popular model with GitHub and GitLab too).

**Comment by bartlettroscoe** [comment]
From: @bernhold 
Sent: Monday, November 2, 2020 9:24 AM
To: @prwolfe, @markcmiller86, @bartlettroscoe, IDEAS-ECP Team
Subject: RE: [Ideas-ecp] [EXTERNAL] An excellent read on problems with pull requests

There are some projects out there which will not accept PRs which are too large.  They’ll ask you to break them up into several smaller ones.  I’m not aware of a fixed size limit.  But both GCC and LLVM work like this, for example.

**Comment by bartlettroscoe** [comment]
From: @bartlettroscoe 
Sent: Tuesday, November 3, 2020 12:57 PM
To: @bernhold, @prwolfe, @markcmiller86, IDEAS-ECP Team
Subject: RE: [Ideas-ecp] [EXTERNAL] An excellent read on problems with pull requests

Okay, so the discussion here is primarily on the size of the change set being reviewed and not really on git, GitHub and PRs themselves which was the primary focus of that long blog article.

I think a much better (and shorter) article that highlights the valuing of reviewing smaller change sets is:

* https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/ 

and the referenced documents (which I just browsed):

* https://smartbear.com/resources/ebooks/the-state-of-code-review-2019/
* https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/ 

(Perhaps these would make a good CC article for BSSw.io?)

The author of the super long blog article:

* https://gregoryszorc.com/blog/2020/01/07/problems-with-pull-requests-and-how-to-fix-them/

seems to suggest that one can fix the problems with large PRs by shifting the focus to reviewing smaller commits in that PR.  But since the entire PR must be reviewed and approved before the PR is merged, it doubt that shifting the focus to reviewing the patches in each and every commit individually will fix the problem.  (In fact, reviewing each and every patch in every commit individually usually increases the total lines of code that must be reviewed compared to the full patch so it might actually be counter-productive to review each patch in detail individually if your goal is to get the reviews done quickly so the merge can take place.)

The solution then is to break up large features and large refactorings into a sequence of smaller incremental changes and associated topic branches and PRs (like David mentioned below).  For example, Kitware used this approach to extend Google Ninja to support Fortran using about 5 PRs (if I remember right).  (Google never would have accepted that refactoring is one large PR.)

Breaking up a larger effort into a number of smaller topic branches with integrations to trunk for each topic branch is something that is hard for Git Feature-Branch Purists to accept.  But focusing on a smaller set of change sets negates the need for a complex commit-based workflow described in the above long blog article.  So let’s just pretend we never read that long article and focus on something like:
   
* https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/ 

😊

-Ross

P.S. The current BSSw.io site is a bit light on deeper content on peer reviews.  In fact, the term “review” is not even present on the top-level list of topics on the page:

* https://bssw.io/

Peer review should be elevated to the same level as testing (which is listed on the front bssw.io page and the top-level list of topic) on the bssw.io site.  (Finding all of the articles on peer-review is a bit hard right now on bssw.io.)

**Comment by rinkug** [comment]
Pr #670 created

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211
