### ISSUE TITLE
How to host BSSw content development process docs

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#568]
How do we manage the BSSw process/workflow documentation?  This relates to how we should handle content like in betterscientificsoftware/betterscientificsoftware.github.io#510.

**Comment by markcmiller86** [comment]
Took following actions to close this issue

- Renamed top level `Documents` to `docs` (as per GitHub pages requirement)
- Copied over jekyll tid-bits from [prototype repo](https://github.com/betterscientificsoftware/bssw-eb-docs2)
- Created `index.md` files in each sub-folder here.
- Renamed and re-organized file content a tad.
- Added to `.travis.yml` CI logic I had tested in [prototype repo](https://github.com/betterscientificsoftware/bssw-eb-docs2). However, it does not appear to be triggering.
- Soon, I will move [prototype repo](https://github.com/betterscientificsoftware/bssw-eb-docs2) to my personal space because there is some cool stuff I had done in it I want to keep around as an example if I ever need it.
