### ISSUE TITLE
Proposed style requirement: DOIs should always be used where possible

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#782]
I believe that wherever possible, DOIs should be provided (and linked).  Pretty much any peer-review paper in the technical literature can be expected to have a DOI.  I believe that we should *always* include a DOI where one is available, and use that in preference to links into any specific publisher/journal/conference site.

Example: a blog author included a "Further Reading" reference to a paper in the IEEExplore service.  The provide link was replaced with the DOI for the paper, obtained from the IEEExplore page for the paper.

I have found that a growing number of books are also assigned DOIs (proceedings published in book form typically have DOIs for each paper, like journals).  Of course the usual unique identifier for books is ISBNs.  And I think we should include those where appropriate as well.

**Comment by bartlettroscoe** [comment]
Looks like I have being doing this already.  For example:

* https://bssw.io/items/what-every-computer-scientist-should-know-about-floating-point-arithmetic

**Comment by rinkug** [comment]
DOIs are mentioned in some of the articles/documents. 

Some material may not have DOI and that is ok. We are not going to be inventing them. If DOIs exist for any resource, then they should be used instead of other links that may go to the same resource.

**Changes to docs: Please mention doi.org or dx.doi.org (basically a DOI resolver) instead of the hosting site (like acm or ieee etc). Example of DOI: https://doi.org/10.1145/103162.103163.** @rinkug to make the edits.

At the labs, tech report gets submitted through OSTI and they get a DOI.
We also get DOI through figshare.

JOSS will give a DOI for each submission
Zenodo and  figshare will allow to hook github code and it will give each release a DOI.
