### ISSUE TITLE
Proposed addition to "An Introduction to Online Learning"

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#798]
The following message came in through our contact form.  Elaine Raybourn is the author of the article.  We need to ask her whether it would be appropriate to add FutureLearn to the article.  If so, it would probably be more appropriate to link to the top level of the platform than the article Becky suggests.

> Hi,
> 
> I came across your landing page at https://bssw.io/items/an-introduction-to-online-learning and noticed you've listed a range of great resources there.
> 
> I work for FutureLearn, and we work with leading universities and organizations around the world to offer our learners relevant, high quality courses across a huge range of topics. In some instances we work with partners to sponsor courses, so that all learners can receive a free certificate and access for as long as it’s on FutureLearn.
> 
> That means that you can show friends, family, colleagues, and potential employers that you’ve completed the course and you’re ready to put your new skills to the test.
> 
> It would be great if you would consider linking to our page at https://www.futurelearn.com/info/blog/free-online-courses-with-certifications-september-2020
> 
> If you’ve got any questions, just let me know.
> 
> Kind regards,
> 
> 
> Becky Hughes
> Publisher Relations Manager

**Comment by rinkug** [comment]
Emailed @elaineraybourn

**Comment by elaineraybourn** [comment]
Future Learn is a MOOC like Udacity and others. There may be python courses (for example) you'd like to link to, but if you link to Future Learn, why not the other MOOCs? My suggestion is that to link to a MOOC, it would be best to take the course (whatever it is) so that one could vouch for the quality of the instruction. You could put out a request to the IDEAS team to see if anyone knows of a course they recommend, otherwise this request to link to the MOOC homepage without suggestion to a specific software engineering course seems out of scope to me.
