### ISSUE TITLE
OpenSSF Best Practices Badge Program

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#807]
Author: @bartlettroscoe 
EB member: @rinkug 

https://bestpractices.coreinfrastructure.org/en is sponsored by the Linux Foundation.  It is a badging program for software best practices.  There are multiple levels, including "passing", silver, and gold.  Criteria are fairly extensive.

I haven't reviewed this thoroughly yet for applicability to scientific software.  I think it is more aimed at system software and such.  But I suspect most or all could be applicable in CSE at some level.  This might be something to discuss a bit in a CC writeup.

**Comment by bartlettroscoe** [comment]
This would make a great CC article (and I am willing to write it).  This is the most though and complete listing of modern best practices for FLOSS that I have ever seen.  It is very hard to argue against these best practices.

I think many of the requirements are satisfied implicitly by just using GitHub or GitLab with issue trackers enabled and assuming a standard GitHub/GitLab workflow.  (We could call-out which of those items are covered in this way.)

This material would be a great driver for PSIPs (@elaineraybourn, @rmmilewi).

The E4S and xSDK community standards should be evaluated to consider these.  (Many of these are already covered in the xSDK Community Policies but many are not.) (@maherou, @jwillenbring).

I actually think this material might be a more complete version of "rate your project" (@jarrah42).  In fact, you can already rate projects at:

* https://bestpractices.coreinfrastructure.org/en/projects

There are already over 3791 projects listed there with scores and badge ratings and progress percentages.  It would be interesting to rate existing projects in our community against the MUST items for the different badge levels and see how they stack up.  I can't find any popular projects in the CSE community that have been rated there (including Kokkos, Spack, HDF5, PETSc, Trilinos, etc.).  But note that someone rated "GCC" and gave it a very low score (but it looks like that was not a real effort to rate it).  Note that [Linux Kernel](https://bestpractices.coreinfrastructure.org/en/projects/34) and [BadgeApp](https://bestpractices.coreinfrastructure.org/en/projects/1) are both given "Gold" ratings (unsurprisingly hopefully).   There are only 7 projects that meet "gold" rating, 17 that meet "silver+" ratings, and 554 that meet "passing+".  So I think what this effort is doing is to try to elevate the issues called out in these items and badge levels.

I have read over all of the different badge levels ("Basic", "Silver" and "Gold") in detail and what is required and recommended in each at:

* https://bestpractices.coreinfrastructure.org/en/criteria

Other than some fairly obvious standard SQA practices (that have been around for 15+ years), you see some interesting items like:

* **Basic**
  * **Quality**
    * **New functionality testing**
      * The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite.
        * => **How many of our projects fail this "Basic" criteria for adding automated tests?  (Hint, at lot.)**
    * **Warning flags**
      * The project MUST address warnings.
        * => **How many of our projects have lots of warnings with major compilers and never fix them?**

* **Silver**
  * **Quality**
    * **Coding standards**
      * The project MUST automatically enforce its selected coding style(s) if there is at least one FLOSS tool that can do so in the selected language(s)
        * => **There are very few CSE projects that do this (or even have a well-defined coding standard that could be checked against)**.
    * **Installation system**
      *  The project MUST provide a way to easily install and uninstall the software produced by the project using a commonly-used convention.
        * => **CMake-based projects do _not_ provide a way to uninstall software so the "uninstall" part is not doable (unless everything is installed into separate directories and then you just delete the new directories).**
    * **Externally-maintained components**
      * The project MUST list external dependencies in a computer-processable way
        * => **Not sure what that means or entails but that is interesting to consider and what implications this has.**
    * **Warning flags**
      * Projects MUST be maximally strict with warnings in the software produced by the project, where practical.
        * => **Boy, a lot of projects don't do this**

* **Gold**
  * **Change Control**
    * **Public version-controlled source repository**
      * The project's source repository MUST use a common distributed version control software (e.g., git or mercurial).
        * => **No SVN allowed!!!**
  * **Quality**
    * **Automated test suite**
      * The project MUST implement continuous integration, where new or changed code is frequently integrated into a central code repository and automated tests are run on the result.
        * => **That means that [Feature Branch] style development with long-lived branches with git is not allowed!!!**

<!--- References --/>

[Feature Branch]: https://martinfowler.com/bliki/FeatureBranch.html

**Comment by bartlettroscoe** [comment]
FYI: I just filled out a submission for TriBITS that can be found at:

* https://bestpractices.coreinfrastructure.org/en/projects?q=TriBITS

With one minor addition ([vulnerability_reports](https://github.com/TriBITSPub/TriBITS/wiki/Kanban-Process-for-Issue-Tracking#vulnerability_reports)) I think TriBITS passes all of the required and suggested practices for the "Passing" level except for:

1. The project sites (website, repository, and download URLs) MUST support HTTPS using TLS.

2. It is SUGGESTED that the Semantic Versioning (SemVer) or Calendar Versioning (CalVer) version numbering format be used for releases. It is SUGGESTED that those who use CalVer include a micro level value.  (TriBITS has not put out any official releases.  Customers instead use almost-continuous integration to get updates of TriBITS.  In the future, official releases may be put out.)

3. The project MUST have at least one primary developer who knows how to design secure software. (See ‘details’ for the exact requirements.)  (I can't honestly answer "Yes" to that question since I have never worked with security-sensitive software.)

For the failure in '1', they have a checker that does not like https://tribits.org and says it is an http site.  (It does not even like https://github.com/TriBITSPub/TriBITS which it says is an http site).

It is trivial to put out a TriBITS release using [semver](https://semver.org) to satisfy '2'.

But satisfying '3' is more problematic.  If you have never developed on security-sensitive software, how can you honestly answer "Yes" to this?  They link to the paper [The Protection of Information in Computer Systems](https://web.mit.edu/Saltzer/www/publications/protection/).  If you read that paper (which is not that long), then can you answer "yes" to this question, even if you never have developed security-sensitive software?  I may read this entire paper and see what I learn.  (Perhaps all software developers should know this stuff, even if you never develop this type of software?)

**Comment by markcmiller86** [comment]
It would be interest to see how many of the criteria could be automated using something like Spack.

Such a thing would be similar to something I toyed with a couple of years ago when Spack was not as mature...

[spack_sqa_metrics3.pdf](https://github.com/betterscientificsoftware/bssw.io/files/6406791/spack_sqa_metrics3.pdf)

**Comment by bartlettroscoe** [comment]
> I think many of the requirements are satisfied implicitly by just using GitHub or GitLab with issue trackers enabled and assuming a standard GitHub/GitLab workflow. (We could call-out which of those items are covered in this way.)

It turns out that that is the case.  In fact, when I did the one for TriBITS, it automatically recognized some standard files in my GitHub repo a checked off those items by default.

>  It would be interest to see how many of the criteria could be automated using something like Spack.

From what I see, I don't think Spack would add much to checking off those items.  The CII Best Practices are mostly about process and documentation.  Spack mostly just automates installs.  The one item were Spack would help is [external_dependencies](https://bestpractices.coreinfrastructure.org/en/criteria#1.external_dependencies).  But TriBITS does that too to some extent as well (but Spack more carefully managing software version requirements).

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board,

I would like to go ahead and write this CC article.  Any objections?  There are two thumbs up so far.

**Comment by bartlettroscoe** [comment]
More interesting links about the foundation for this:

* https://changelog.com/podcast/215
* https://www.infoworld.com/article/3065982/linux-foundation-tackles-open-source-security-with-new-badge-program.html
* https://www.zdnet.com/article/linux-foundation-and-harvard-announce-linux-and-open-source-contributor-security-survey/
* https://www.linux.com/featured/why-cii-best-practices-gold-badges-are-important/
* https://lwn.net/Articles/690169/
* https://www.cio.com/article/3065228/cii-s-best-practices-badge-program-is-making-open-source-projects-more-secure.html
* https://blogs.oracle.com/r/should-r-consortium-recommend-cii-best-practices-badge-for-r-packages-latest-survey-results
* https://www.reddit.com/r/datasets/comments/93yioc/metadata_on_1729_software_projects_with_linux/
* https://medium.com/zephyrfoundation/developing-badge-worthy-standards-52a80d89ff45
* https://fossid.com/blog/recommended-practices-for-developers-using-github/

Projects that brag about earning a passing CII best practices badge:

* https://chaoss.community/metric-cii-best-practices-badge/
* https://www.r-consortium.org/r-consortium-project/2018/08/16/cii-best-practices-badge-for-r-packages-responding-to-concerns
* https://www.lfenergy.org/blog/2021/05/05/powsybl-has-achieved-the-cii-best-practices-badge/
* https://www.lfedge.org/2021/03/16/home-edge-earns-the-cii-best-practices-badge/
* https://research.samsung.com/blog/Home-Edge-has-achieved-CII-Best-Practices-passing-badge
* https://backdropcms.org/news/backdrop-cms-earns-a-best-practices-badge-from-the-linux-foundation-core-infrastructure
* https://www.businesswire.com/news/home/20160725005133/en/OpenStack-Earns-Core-Infrastructure-Initiative-Best-Practices-Badge-for-Security-Quality-and-Stability
* https://www.openstack.org/news/view/243/openstack-earns-core-infrastructure-initiative-best-practices-badge-for-security,-quality-and-stability
* https://www.linuxfoundation.jp/blog/2020/06/linux-kernel-earns-cii-best-practices-gold-badge/
* https://geodynamics.org/cig/dev/code-donation/checklist/
* https://dgshow.org/tags/badge%20program/rss

Related badges:

* https://www.comses.net/resources/open-code-badge/
* ???

**Comment by bartlettroscoe** [comment]
There are 23K hits for https://bestpractices.coreinfrastructure.org on github.com:

* https://github.com/search?l=&q=https%3A%2F%2Fbestpractices.coreinfrastructure.org&type=code

That suggests this is a very popular listing of best practices and many projects are displaying badges.

**Comment by bartlettroscoe** [comment]
FYI: The silver-level item:

*  The project MUST be able to repeat the process of generating information from source files and get exactly the same bit-for-bit result. If no building occurs (e.g., scripting languages where the source code is used directly instead of being compiled), select "not applicable" (N/A). {N/A justification} {Met justification} [[build_repeatable](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.build_repeatable)]

in the "Details" provides a link to:

* https://reproducible-builds.org/

**Comment by bartlettroscoe** [comment]
This is more than a CC article.  At the minimum, this needs to be a short article if not a blog article.  The more I look at this the more impressed I am and the more I think IDEAS-ECP need to leverage this.   The rateyourproject.org site is a nice high-level quick triage of a project but the CII Best Practices are how you actually improve in those areas and are more carefully thought out  add screened by a larger number of developers from a diverse set of projects.  The only question is how to adapt these to less-than open-source software (that do not have a fully open source licenses and do not have open repos or open websites).  (The question of security requirements will be addressed in betterscientificsoftware/bssw-blog-planning#91.)

**Comment by bernhold** [comment]
Well, I think it would be good to simply point to the resource as a CC.  That's what CC is for, and it gets it onto the site sooner rather than later.

Then we can riff on it all we like, with takes on security and how to apply it scientific software, etc. as original content.

It would be good to include Greg Watson and Addi Malviya Thakur in discussions of how to build on this.  I believe they're trying to use it within their ORNL groups (RSEs).

**Comment by bartlettroscoe** [comment]
From [[dco](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.dco)] I just learned that they have finally solved the legal problem of accepting contributions in accordance with the software license.  It is to use a Developer Certificate of Origin (DCO) and a "signed-off" feature with [`git commit --signoff`](https://git-scm.com/docs/git-commit).  And there is a GitHub Action to enforce this in PRs (see https://github.com/probot/dco).  Finally, this problem is solved!  NOTE: [[dco](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.dco)] is a SHOULD item and is not required.  (But SHOULD items need to be implemented unless there is a good reason not to do so and most projects don't have an excuse not to.)

**Comment by bartlettroscoe** [comment]
> Well, I think it would be good to simply point to the resource as a CC. That's what CC is for, and it gets it onto the site sooner rather than later.

@bernhold, that sounds reasonable.

**Comment by bartlettroscoe** [comment]
It occurred to me that a custom version of the CII Best Practices Badge site would be great for internal projects at various institutions.  To ask that question, I posted https://github.com/coreinfrastructure/best-practices-badge/issues/1635.

**Comment by bartlettroscoe** [comment]
One benefit I am finding to the BadgeApp is that the criteria become a road map for a project.  For example, I was looking for implementation information for the BadgeApp itself and I remembered there was an item for that (documentation_architecture).  I opened up:

* https://bestpractices.coreinfrastructure.org/en/projects/1?criteria_level=1

and found the following link under [documentation_architecture]:

* https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/implementation.md

This is really nice.  So the BadgeApp entry for a project provides a type of standard index into a project to make it easy to find standard information about that project.

**Comment by bartlettroscoe** [comment]
FYI: I am getting some good responses from the main guy responsible for the CII Best Practices in https://github.com/coreinfrastructure/best-practices-badge/issues/1635.  I need to meet with Greg Watson to follow-up with him since he said he looked at these.

**Comment by bartlettroscoe** [comment]
FYI: I am working on a short article (not a CC article) for this right now.

BTW, I just realized that the CII is no more and now there is the OpenSSF and it is not clear what the status of this CII Best Practice Badge Program really is at this point.  See https://github.com/coreinfrastructure/best-practices-badge/issues/1515#issuecomment-904636952.

**Comment by bartlettroscoe** [comment]
> BTW, I just realized that the CII is no more and now there is the OpenSSF and it is not clear what the status of this CII Best Practice Badge Program really is at this point. See coreinfrastructure/best-practices-badge#1515 (comment).

Turns out there was no need for concern.  It is make clear in a couple of places that the CII Best Practices Badge Program is continuing under the OpenSSF and the head of that effort even modified the troublesome page https://www.coreinfrastructure.org/ based on my inquiry (see https://github.com/coreinfrastructure/best-practices-badge/issues/1515#issuecomment-905006684).  The issue is that "CII Best Practices Badge Program" is so well branded and well accepted that it can't have its name changed at this point even through the "CII" program the birthed it is actually dead.

Back to writing the short article ...

**Comment by bartlettroscoe** [comment]
FYI: This article is turning out to be several pages and I am working to tighten it up to have the proper impact.  As such, I don't want to rush this for this month's BSSw digest and I want to allow enough time to review.

I will propose to do a short CC article in it's place.

**Comment by bartlettroscoe** [comment]
Item is published:

* https://bssw.io/items/openssf-best-practices-badge-program
