### ISSUE TITLE
Consider alternative styling for references

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#861]
**Blocked by:** #702, #779

## Description

The CSS for the bssw.io site includes a `references-wrapper` class and a `references` class.  Together, these can be used to render a list of references in a smaller font, with a two-column format.

Matt Stone put together an example of how this would look for the GPU blog we just published.
* Source: <https://github.com/betterscientificsoftware/bssw.io/blob/c91d51da9309f180e54a8ad52e23e583afa3df41/Articles/Blog/2021-05-RefTest_GPUProgramming.md>
* Preview: <https://preview.bssw.io/blog_posts/a-test-for-references-see-very-bottom-of-post>
* Default styling: <https://preview.bssw.io/blog_posts/a-gentle-introduction-to-gpu-programming>

If we decide we prefer the two-column format, it would be nice for the wikizie tool to automatically generate the correct markup.  And if that's not easily possible, it may argue against adoption this formatting.

**Comment by markcmiller86** [comment]
Well, these examples do not appear to be "working" at least in the sense that the main content footnotes are linking to actual referneces.

To me, the question of CSS styling is (or at least should be) mostly orthogonal to markdown composition. And what I and @bartlettroscoe have worked to develop is a fairly simple, mostly markdown-only way to enable authors to easily operate in markdown and have the rendered result in markdown look and behavior fairly reasonbly. In fact, the only way I think it could be made simpler from an author's standpoint is to use a markdown implementation that supports carrot-based (`^foo`) footnotes (e.g. this example of a footnote^foo). Most don't. Some do. So, we wind up using `<sup>...</sup>`. 

The `wikize_refs.py` tool takes the author's footnotes as well as the list of citations those footnotes reference (which ordinarily would not be rendered by markdown at all because they are reference style links) and creates a new markdown file that makes the list of citations visible in markdown *and* with good additional behaviors (e.g. hover-text, two-level linking). All that should also be achievable with CSS on the backend but that doesn't do anything for composing, previewing or browsing the originating markdown.

We can enhance `wikize_refs.py` to include one new behavior I see here, two column table of refs. Thats easy...a new command-line switch and a slight adjustment in some of the generated output. BTW...the one rendered in examples here have way too much horiz. white-space (a premium resource) and extends past the right margin and is reminiscent of the basic problem the back-end seems to have with tables. We can also enhance `wikize_refs.py` to include tell-tale designators the backend can trigger off of to decide which CSS styles to use when the page is generated.

After reading [this ref](https://v4.chriskrycho.com/2015/academic-markdown-and-citations.html) on a fairly complex workflow for handling citations in markdown, I am feeling more and more like `wikize_refs.py` (or a suitable successor) might have legs of its own as a wholly separate tool, especially if its enhanced to support a few additional features (`^xxx` MD styling for footnotes as well as swapping between such stylings, one or two column list of refs/citations and citations *databases* which would basically be markdown files containing *only* reference style links. That isn't a BSSw activity (unless someone requested it) but is something I am apt to do with my *free time*.

**Comment by bartlettroscoe** [comment]
I vote for a Markdown-centric solution for citations in Markdown files.  Creating an option in `wikize_refs.py` for a table is fine.  I don't think it is a good idea to depend too much on customizations of the bssw.io site.  (The most that we should expect is that the bssw.io site generator handle Markdown in a reasonable way consistent with other Markdown renderers.)

**Comment by bernhold** [comment]
Okay, sorry about that.  I hadn't looked closely at what Matt had done and he really did break it.  I made a version that uses his CSS style but where the references actually work:
* Working alternative: <https://preview.bssw.io/blog_posts/a-better-test-for-references-see-very-bottom-of-post>
*  Working alternative source: <https://github.com/betterscientificsoftware/bssw.io/blob/sbxchicago-patch-1/Articles/Blog/2021-05-reftest2.md>

I also see that Mark's already made a variation, but I'll let him comment on that.

**Comment by bernhold** [comment]
For my part, I actually like the smaller font in Matt's styling for the references.  I'm ambivalent about two columns vs one.  I think one column with the smaller font would be fine if that's a useful compromise.  That would entail somehow indicating that we're in Reference styling -- either a `<div>` of some kind, or perhaps using the `### References` header to trigger it (just as other headers trigger special processing in the front-end).  In fact if it were triggered by the presence of the header, perhaps we could go back to the pure markdown in the source.

I'm pretty sure we could also do away with the automatic generation of the numerical labels in the CSS and just use what wikize generates.  That would remove the other point of differentiation from a general wikize solution.

Of course this is predicated on others preferring Matt's styling over the default.  So maybe that's the first point to decide?

**Comment by markcmiller86** [comment]
Ok, yep, that is working now. I do like the smaller font. In the examples here it looks like that is getting applied *only* to the title text, not the numbering of the footnotes which, as an aside, I think would be better to remove as being a column in the table.

In any event, I am certain just a few lines of CSS styling on the back-end solves the font sizing issue and authors should still code citations and refs as we currently do or largely so. I don't see any changes in how authors compose md content. I do see some things we can do to `wikize_refs.py` to improve things more.

**Comment by bartlettroscoe** [comment]
@markcmiller86, @bernhold,

IMHO, the table of references at:

* https://preview.bssw.io/blog_posts/a-test-for-references-see-very-bottom-of-post

does not look all that much better than the simple table at:

* https://bssw.io/items/working-effectively-with-legacy-code

It is at the bottom of the page and who cares how much screen real-estate it takes at the bottom.

IMHO, the primary goal should be to make it easy to debug an `*.md` file by just looking at the GitHub rendering of that file and then not have to worry too much about how many changes (and screwups) occur when this gets rendered by the bssw.io site generator.  It is fast and easy to fix problems that demonstrate themselves in on GitHub and it is a pain in the rear to address problems that only demonstrate themselves on bssw.io.  Anything that makes you have to go back and forth changing things in an `*.md` file, then merging to the 'preview' branch (and hoping GHA does not crash), then manually regenerating the preview.bssw.io site  (then waiting 5 minutes), then looking at the generated file on the priview.bssw.io site (then doing it all over again and again until the problems are fixed) is a step backwards.

I really wish that the bssw.io site generator could just use Jekyll (with a theme) for the basic formatting of a given `*.md` file and then layer on to that the other features desired for the bssw.io site.  That would make it possible to view what the pages look like locally on your own machine and then there would be almost zero surprises when it was put up on the bssw.io site.  This is really important for the sustainability of the bssw.io site after the end of ECP, IMHO.

**Comment by bernhold** [comment]
@bartlettroscoe, our lead designers, Matt, has a different sensibility than you do.  The desirable features he sees in his proposal are:
* It limits scrolling (small font, two columns)
  - Even though it is at the end of the article, he considers this important/useful
* It provides the proper emphasis to citations (they're less important so they're smaller in size)
* It build on the styling of ordered lists
  - Tables are *not* a desirable solution here for a number of reasons.
  - I think his intent is that the size of the numbers match the size of the reference body text, though I think something is wrong with that as it is currently written.

Personally, though I often disagree with Matt on design issues, I realize that he's the professional and I'm most definitely not.  But for better or worse in this case, I'm mostly on Matt's side.  I like the small-font two-column presentation much more than I like the table.  Others may of course differ.

But for you and @markcmiller86, why not a simple ordered list instead of a table?  If that's okay for the authoring view, then I think it would be a small step to implement CSS styling that provides the smaller font.  As I've said, I don't know how hard it would be to implement the two-column formatting in pure CSS, but I think it is possible.

**Comment by markcmiller86** [comment]
> But for you and @markcmiller86, why not a simple ordered list instead of a table?

We can do that. Thats a simple change to `wikize_refs.py` when it generates the *visible* markdown content from the IN*visible* list of reference links

**Comment by bernhold** [comment]
Discussed on 2021-05-27 EB call.  Summary...

* Ordered list format (as opposed to table) is fine, probably better.
* Matt's current CSS has a couple of issues, but overall we like it
  - Numbers are too large (not consistent with reference text)
  - Space between numbers and reference text is too large
 * Number could also be styled as a superscript, as is used in many journals
 * It would be nice if the CSS could responsively make the list 1-column or 2 without additional markup on our part.
   - We can make wikize_refs generate what is needed, but it makes the tool less general and more fragile
 * Wikize_refs can generate whatever is needed to key the front-end/CSS to treat the content as references
   - Currently, it generates the References header, and if that suffices, it would be great

**Comment by bernhold** [comment]
#859 is connected to this

**Comment by markcmiller86** [comment]
I believe this will be addressed by #927 also.
