### ISSUE TITLE
Building Software Together book

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#865]
@author: pagrubel
This is a new online book from Greg Wilson, available under a Creative Commons license.  It is aimed at undergraduate students embarking on their first "project" course.  It might be useful to others as well, and thus might be a good CC resource.

https://buildtogether.tech/

**Comment by pagrubel** [comment]
After skimming this and reading some of it, I think it should have a larger audience than undergrads. It has some useful insights and things to be reminded of.

**Comment by bartlettroscoe** [comment]
This is an online book that is managed on GithHub and published with a Jekyll site.  (Which is how I am targeting publishing my "Git Design Patterns" book so it is nice to see the pattern.)

From skimming a few sections in https://buildtogether.tech and doing some Google searches using `site:https://buildtogether.tech <keyword>`, this is very high-level material.  But the target audience is complete newbies as per the statement in the introduction:

> If you are an undergraduate student embarking on a semester-long software project as part of a team, this book will give you tools that will help you succeed.

Given that, I think this could use some more work.  Just looking over the Git material in:

* https://buildtogether.tech/git-solo/
* https://buildtogether.tech/git-team/

it is showing operations like explicit pulls from the main branch like:

```
$ git pull origin main
```

But no one uses Git like this.  Git sets up tracking branches (by default) and one should understand what those are and use those to simplify one's workflows.  That just makes the basic Git workflows simpler and less error-prone.  And this really needs to highlight the usage of the [git prompt and shell completion scripts](https://bssw.io/items/critical-beginner-git-usage-tips#minimal-setup) as that makes git much easier to use (especially for Git newbies).

Here are some bits of info you can get by studying the GitHub repo for the book at https://github.com/gvwilson/buildtogether.tech:

* The majority of the work on the book (over 95% of it) was done between 2/28/2021 and 4/25/2021, so it is a very new book
* So far, the GitHub repo has 4 forks and 4 stars
* There have been only 3 PRs from external people (2 were merged, one was rejected)
* Of the 137 GitHub Issues, 85 were created by the author, and 48 were created by a single other person to suggest improvements (who should have just used one or two PRs).  Other than that, just 4 other people have submitted 4 issues and of those, 2 issues have not received any comments from the author.  (This suggests the author may not be as open to feedback.)

This makes it seem this is a very new book that may not have had much external feedback yet.

If we do create a CC article for this, we should emphasize:

* This is an online book that is managed with GitHub and updated online at will by the author
* This is a very new book and readers should provide feedback and suggestions to the author through GitHub Issues and PRs

With those called out in the CC article, I would say we should publish a CC article for this book.

<details>

<summary><b>Some more detailed analysis of GitHub Issues</b> (Click to expand)</summary>

.

Let's look at the contributions and issues on GitHub.  First, if you look at:

* https://github.com/gvwilson/buildtogether.tech/graphs/contributors

you will see that of the over 250 commits, only two commits came from other people (one commit each) and those were very minor typo corrections.

Of the 137 total Issues shown at:

* https://github.com/gvwilson/buildtogether.tech/issues?q=is%3Aopen+is%3Aissue

85 of them are reported by the `@gvwilson` leaving just 52 issues: as shown at:

* https://github.com/gvwilson/buildtogether.tech/issues?q=is%3Aopen+is%3Aissue+-author%3Agvwilson+

But of those 52 remaining Issues, 48 of those were from one author `@RituKapur-Developer` as shown at:

* https://github.com/gvwilson/buildtogether.tech/issues?q=is%3Aissue+author%3ARituKapur-Developer++is%3Aclosed+

It looks like `@RituKapur-Developer` was using a bunch of GitHub Issues instead of a proper PR to suggest changes to mostly the "Fair Play" and "How to Join and Existing Project" chapters.  This is not a great example of the usage of GitHub.

So that leaves just 4 other issues and 2 of those are still open with no comments from the author of the book.

But there are some recent commits by the author of the book as recent as Nov 23, 2021 and issues creates by them as recent as  June 20, 2021 so it seems the book is being maintained.

</details>

**Comment by rinkug** [comment]
This website is down. And I dont see any mention of this book except for a tweet. I believe the book is no longer available.
