### ISSUE TITLE
BSSw.io: Relative vs. Absolute internal links

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#866]
Several times, BSSw.io content will refer to internals links within the BSSw.io site.  We need such internal links to be relative (for ex: "../../blog/foo.md) rather than absolute (for ex: https://bssw.io/)

Action items:

1. * Add documentation about this in the EB docs
2. * Change links in all articles.

**Comment by bernhold** [comment]
Offhand, there may be a challenge here in that directory structure of the repo is *not* the same as that implicit in the web site.  So a relative link in the source would not be the link you need to make in the published content.

I can see three ways to solve this:
1. Change the directory structure implicit in the front-end to match the repo.  This would move lots of content around and break bookmarked links to a lot of content
2. Change the repo directory structure to match the front-end.  This is actually not a bad idea, but I don't think it provides some of the differentiation of content types that is useful in the repo to guide contributors to the right templates, etc.
3. Require the front-end to map relative links within the content.  This is quite feasible, but requires PC to implement and runs counter to my preference to simplify the front-end rather than complicate it.  But it is not so different from what they're doing to support relative URLs for images.

**Comment by bernhold** [comment]
@rinkug is SBX/PC really waiting on our input for this?  I haven't seen this come up on the Basecamp list.  It is possible that it has come up in other communications.

But it seems to me that the next step is an EB discussion to understand the motivation and requirements here before we initiate discussion with SBX/PC about.

Do we need a working group for this?
