### ISSUE TITLE
Git worktree CC has fallen behind a login-wall

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#944]
I don't know about others but I loath having to sign up, even if its free, to utilize a *free* online resource. That invariably means it ain't free. There **WILL BE** a cost to me, somehow, as they collect and then sell my contact information, etc.

I mention this because I just now noticed that an article I sited from [here](https://bssw.io/items/working-within-multiple-git-branches-simultaneously) appears to have now fallen behind such a login-wall. I don't like it. I wonder if I should seek some other replacement CC reference for it.

**Comment by bernhold** [comment]
We had a conversation in the early days of the Editorial Board about paywalled resources.  I think it tailed off rather than reaching a clear resolution.  If we want to resurrect this discussion in a general sense, we should probably create an issue for that purpose.

Personally, I think we should *prefer* more accessible resources, I don't think we should shy away from referencing useful resources that require registration or even require payment.  After all, we recommend books, which are rarely freely available.  Readers can decide their own cost thresholds.

So for this article in particular, my recommendation would be to do some searching for a more accessible description of worktree and *add* (rather than replace) to the article. But if you can't find one, don't fret it.

**Comment by bernhold** [comment]
@markcmiller86 can we close this issue?

**Comment by markcmiller86** [comment]
Sure thing. FWIW...the referenced article does not now appear to be behind a login-wall. Maybe I hit a reference limit when I saw this before.
